
### list
GET https://64460b4b0431e885f00863ca.mockapi.io/api/v1/users HTTP/1.1



### Add

POST https://64460b4b0431e885f00863ca.mockapi.io/api/v1/users HTTP/1.1

content-type: application/json

{
 "name": "Mr Nhan",
 "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/684.jpg",
 "email": "nhan@example.net",

}


###
POST https://my-json-server.typicode.com/nhannn87dn/ReactJs-Basic-Tutorials/products HTTP/1.1
content-type: application/json

{
    "name": "Robot Hút Bụi Lau Nhà Xiaomi Roborock S7",
    "thumbnail": "https://raw.githubusercontent.com/nhannn87dn/ReactJs-Basic-Tutorials/main/5.Demo-Projects/images/robot-hut-bui-lau-nha-xiaomi-roborock-s7-thumb.jpg",
    "price": "6550000.00",
    "salePrice": "0",
    "category": "2"
}


### Login

POST https://dummyjson.com/auth/login  HTTP/1.1
content-type: application/json

{
    "username": "kminchelle",
    "password": "0lelplR"
}

### Login
POST https://api.escuelajs.co/api/v1/auth/login HTTP/1.1
content-type: application/json

# Body
{
  "email": "john@mail.com",
  "password": "changeme"
}


### get User
GET https://api.escuelajs.co/api/v1/auth/profile HTTP/1.1
#Heaer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY4MjMyNjE5MSwiZXhwIjoxNjg0MDU0MTkxfQ.A7VomrPxchWUjEhcG43Fbr_Wrn6CyasqKZ2oLK_lCJo