# Gọi API, Gửi một request đến URL bên dưới
# với phương thức GET

GET https://api.escuelajs.co/api/v1/products 

# GET --> Lấy danh sách, 
# POST --> Tạo mới
# PUT --> Update, chỉnh sửa
# DELETE --> Xóa

# Thêm mới một sản phẩm
###
POST https://api.escuelajs.co/api/v1/products/
content-type: application/json

{
  "title": "New Product 36",
  "price": 36,
  "description": "A description 36",
  "categoryId": 1,
  "images": ["https://placeimg.com/640/480/any"]
}