POST https://dummyjson.com/auth/login
Content-Type: application/json

{
    "username": "emilys",
    "password": "emilyspass"
}

### get Profile
GET https://dummyjson.com/auth/me
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3ODc3Mjg2NjIsImV4cCI6MTc4NzczMjI2Mn0.b2xMBtAbFk2PV44npdFhrm0z0s6eZZtIFmvRE9AoKko





#### Login
POST https://training.softech.cloud/api/training/users/login
Content-Type: application/json

{
  "username": "tungnt",
  "password": "123456789"
}